apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Release.Name }}-cron
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            envFrom: 
            - configMapRef:
                name: {{ .Release.Name }}-config
            command:
              - sh
              - -c
              - |
                while true; do
                  echo "$LOG_MESSAGE"
                  sleep 60
                done