apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Release.Name }}-cron
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["/bin/sh", "-c"]
            args:
              - cat /config/LOG_MESSAGE; sleep 30
            volumeMounts:
            - name: log-config-volume
              mountPath: /config
          volumes:
          - name: log-config-volume
            configMap:
              name: {{ .Release.Name }}-config
